# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              
description:        On this platform diverse accessibility instruments are collected to foster networking and bridge the gap between research and practice. 
lang:               en

# Site subpath, e.g. /blog
baseurl:           

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                ""

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:               

navbar:
  sticky: true
  
# Default footer image settings
footer:
    copyright:      Copyright 2020

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate:           10

# Blog path
paginate_path:      "/blog/:num/"
  
tool:
  excerpt_length:   194
# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src

sass:
  style:            compressed

collections:
  tools:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _pages
  - scope:
      path:         ""
      type:         pages
    values:
      layout:       page
